package me.imguralbumdownloader.com;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Toolkit;

/**
 * 
 * @author Micah Lee
 * AboutWindow displays a message about the ImgurAlbumDownloader
 *
 */
public class AboutWindow extends JDialog {
	private static final long serialVersionUID = 1L;
	private final JPanel contentPanel = new JPanel();
	
	/**
	 * Constructor
	 */
	public AboutWindow() {
		setResizable(false);
		//Set window attributes
		setTitle("About");
		setIconImage(Toolkit.getDefaultToolkit().getImage(AboutWindow.class.getResource("/me/imguralbumdownloader/com/icon-imgur.png")));
		setBounds(100, 100, 420, 126);
		getContentPane().setLayout(new BorderLayout());
		contentPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		getContentPane().add(contentPanel, BorderLayout.CENTER);
		
		//Create content for window
		JLabel lblMadeByMicah = new JLabel("This is just a simple imgur album downloader made by Micah lee");
		JLabel lblThanksForTrying = new JLabel("Thanks for trying my project out!");
		JButton btnOk = new JButton("OK");
		
		//Dispose of window when "OK" button has been pressed
		btnOk.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				dispose();
			}
		});
		
		//Set up the GroupLayout (Auto generated by Eclipse Window Builder)
		setLocationRelativeTo(null);
		GroupLayout gl_contentPanel = new GroupLayout(contentPanel);
		gl_contentPanel.setHorizontalGroup(
			gl_contentPanel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPanel.createSequentialGroup()
					.addGroup(gl_contentPanel.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_contentPanel.createSequentialGroup()
							.addContainerGap()
							.addGroup(gl_contentPanel.createParallelGroup(Alignment.LEADING)
								.addComponent(lblMadeByMicah)
								.addComponent(lblThanksForTrying)))
						.addGroup(gl_contentPanel.createSequentialGroup()
							.addGap(142)
							.addComponent(btnOk, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(83, Short.MAX_VALUE))
		);
		gl_contentPanel.setVerticalGroup(
			gl_contentPanel.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPanel.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblMadeByMicah)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(lblThanksForTrying)
					.addPreferredGap(ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
					.addComponent(btnOk)
					.addContainerGap())
		);
		contentPanel.setLayout(gl_contentPanel);
	}
}
