package me.imguralbumdownloader.com;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;

public class DownloadingWindow extends JFrame {
	private static final long serialVersionUID = 1L;
	private JPanel contentPane;
	private JProgressBar progressBar;
	private JLabel nowDownloading;
	private JLabel fileName;
	private JButton cancelDownload;
	private JButton background;
	private ImgurAlbumDownloader iad;
	
	/**
	 * Constructor
	 * @param url - String - the url to be downloaded from
	 * @param downloadPath - String - where the files will be downloaded
	 */
	public DownloadingWindow(final String url, final String downloadPath) {
		//Set window attributes
		setResizable(false);
		setIconImage(Toolkit.getDefaultToolkit().getImage(DownloadingWindow.class.getResource("/me/imguralbumdownloader/com/icon-imgur.png")));
		setTitle("Downloading...");
		setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
		setBounds(100, 100, 439, 134);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		
		//Set and create window content
		nowDownloading = new JLabel();
		progressBar = new JProgressBar();
		cancelDownload = new JButton("Cancel Download");
		background = new JButton("Download in Background");
		fileName = new JLabel("File Name");
		
		//Get the file type from ImgurWindow and create the ImgurAlbumDownloader thread based on the file type
		switch(ImgurWindow.getFileType()){
			case "all":
				iad = new ImgurAlbumDownloader(url, downloadPath, ImgurAlbumDownloader.all, this);
				break;
			case "jpg":
				iad = new ImgurAlbumDownloader(url, downloadPath, ImgurAlbumDownloader.jpgs, this);
				break;
			case "gif":
				iad = new ImgurAlbumDownloader(url, downloadPath, ImgurAlbumDownloader.gifs, this);
				break;
			case "png":
				iad = new ImgurAlbumDownloader(url, downloadPath, ImgurAlbumDownloader.pngs, this);
				break;
			case "webm/mp4":
				iad = new ImgurAlbumDownloader(url, downloadPath, ImgurAlbumDownloader.webm, this);
				break;
		}
		//Setup the Group Layout (Auto generated by Eclipse Window Builder)
		setLocationRelativeTo(null);
		GroupLayout gl_contentPane = new GroupLayout(contentPane);
		gl_contentPane.setHorizontalGroup(
			gl_contentPane.createParallelGroup(Alignment.TRAILING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_contentPane.createSequentialGroup()
							.addContainerGap()
							.addGroup(gl_contentPane.createParallelGroup(Alignment.LEADING)
								.addComponent(nowDownloading, GroupLayout.PREFERRED_SIZE, 335, GroupLayout.PREFERRED_SIZE)
								.addComponent(fileName)
								.addComponent(progressBar, GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)))
						.addGroup(gl_contentPane.createSequentialGroup()
							.addGap(71)
							.addComponent(background)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(cancelDownload)))
					.addContainerGap())
		);
		gl_contentPane.setVerticalGroup(
			gl_contentPane.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addComponent(nowDownloading, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(fileName)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(progressBar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.BASELINE)
						.addComponent(background)
						.addComponent(cancelDownload))
					.addContainerGap(20, Short.MAX_VALUE))
		);
		contentPane.setLayout(gl_contentPane);
		//Activate the listeners
		activateListeners();
		//Start the download
		new Thread(iad).start();
	}
	
	/**
	 * activateListeners will set up all the ActionListeners for the content in this window
	 */
	private void activateListeners(){
		//If the user clicks the Download in Background button then the window will hide
		background.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				setVisible(false);
			}	
		});
		
		//If the user clicks the Cancel Download button, then the respective ImgurAlbumDownloader
		//thread's download will be discontinued by setting continueDownload to false
		cancelDownload.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to cancel the download?", "", JOptionPane.YES_NO_OPTION);
				if(confirmed == JOptionPane.YES_OPTION){
					iad.continueDownload = false;
				}
			}	
		});
		
		//If the user tries to exit the window, a prompt will show to prevent any unwanted activity
		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent e) {
				int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?\nAny unfinished downloads will cancel.", "", JOptionPane.YES_NO_OPTION);
			    if (confirmed == JOptionPane.YES_OPTION) {
			    	iad.continueDownload = false;
			    }
			}
		});
	}
	
	//Set the text to show which album is downloading
	public void setDownloading(String s){
		nowDownloading.setText(s);
	}
	
	//Set the text to show which file is being downloaded
	public void setFile(String s){
		fileName.setText(s);
	}
	
	//Set how many files to be downloaded for the progres bar
	public void setFileCount(int i){
		progressBar.setMinimum(0);
		progressBar.setMaximum(i);
	}
	
	//Increment the progress bar when a file has completed
	public void incrementProgress(int i){
		progressBar.setValue(i);
	}
}
