package me.imguralbumdownloader.com;

import java.awt.BorderLayout;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextPane;

import java.awt.SystemColor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Toolkit;
import javax.swing.SwingConstants;
import org.eclipse.wb.swing.FocusTraversalOnArray;
import java.awt.Component;

/**
 * 
 * @author Micah Lee
 * HelpWindow displays a helpful message about the usage of ImgurAlbumDownloader
 *
 */
public class HelpWindow extends JDialog {
	private static final long serialVersionUID = 1L;
	private final JPanel contentPanel = new JPanel();
	
	/**
	 * Constructor
	 */
	public HelpWindow() {
		//Set window attributes
		setTitle("Help");
		setIconImage(Toolkit.getDefaultToolkit().getImage(HelpWindow.class.getResource("/me/imguralbumdownloader/com/icon-imgur.png")));
		setModal(true);
		setBounds(100, 100, 480, 271);
		getContentPane().setLayout(new BorderLayout());
		contentPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		getContentPane().add(contentPanel, BorderLayout.CENTER);
		
		//Create window content
		JTextPane txtpnYouCanSet = new JTextPane();
		txtpnYouCanSet.setBackground(SystemColor.control);
		txtpnYouCanSet.setEditable(false);
		txtpnYouCanSet.setText("You can set where your selected imgur album is downloaded to by clicking the Set Path button. This will open up a window where you can choose the directory to save the album. The downloader will automatically create a new folder for your images.\r\n\r\nOnce you have found your imgur album url (http://imgur.com/a/xxxxx) enter it into the text field labeled Imgur URL. Set which file types you want to download by using the drop down menu next to the text field (\"all\" will download all image types including ones not shown). \r\n\r\nOnce you have your downloader set up, simply hit download. This will open up a new window, and you can continue downloading any other albums you may want to download.\r\n\r\nThanks for using Imgur Album Downloader!");
		
		JButton btnOk = new JButton("OK");
		//Dispose when user presses "OK" button
		btnOk.setVerticalAlignment(SwingConstants.BOTTOM);
		btnOk.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent arg0) {
				dispose();
			}
		});
		
		//Set up the GroupLayout (Auto generated by Eclipse Window Builder)
		setLocationRelativeTo(null);
		GroupLayout gl_contentPanel = new GroupLayout(contentPanel);
		gl_contentPanel.setHorizontalGroup(
			gl_contentPanel.createParallelGroup(Alignment.TRAILING)
				.addGroup(gl_contentPanel.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(txtpnYouCanSet, GroupLayout.PREFERRED_SIZE, 442, GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
				.addGroup(Alignment.LEADING, gl_contentPanel.createSequentialGroup()
					.addGap(174)
					.addComponent(btnOk, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(188, Short.MAX_VALUE))
		);
		gl_contentPanel.setVerticalGroup(
			gl_contentPanel.createParallelGroup(Alignment.TRAILING)
				.addGroup(Alignment.LEADING, gl_contentPanel.createSequentialGroup()
					.addComponent(txtpnYouCanSet, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(btnOk)
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		contentPanel.setLayout(gl_contentPanel);
		contentPanel.setFocusTraversalPolicy(new FocusTraversalOnArray(new Component[]{btnOk}));
		setFocusTraversalPolicy(new FocusTraversalOnArray(new Component[]{btnOk}));
		
		btnOk.requestFocusInWindow();
		btnOk.requestFocus();
	}
}
